services:
  - type: web
    name: question-paper-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: DB_NAME
        value: question_paper_db
      - key: REQUEST_COLLECTION
        value: question_requests
      - key: PAPER_COLLECTION
        value: question_papers
      - key: FEEDBACK_COLLECTION
        value: paper_feedback
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: AWS_ACCESS_KEY_ID
        value: ${AWS_ACCESS_KEY_ID}
      - key: AWS_SECRET_ACCESS_KEY
        value: ${AWS_SECRET_ACCESS_KEY}
      - key: AWS_REGION
        value: ${AWS_REGION}
      - key: S3_BUCKET_NAME
        value: ${S3_BUCKET_NAME} 